name: dander
description: "Fog-of-war neighbourhood explorer app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^13.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  go_router: ^15.1.2
  provider: ^6.1.5
  uuid: ^4.5.1
  get_it: ^8.0.3
  http: ^1.2.0
  share_plus: ^10.0.0
  connectivity_plus: ^6.0.0
  google_fonts: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
